version: "3"

services:
  db:
    build: "./"
    volumes:
      - "./db/data:/var/lib/mysql"
    environment:
      - TZ=Asia/Bangkok
      - LANG=C.UTF-8

  backend:
    build:
      context: "./backend"
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - "./backend/.env"
    restart: on-failure
    environment:
      - MYSQL_USER=us3admin
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=oasip

  nginx:
    build:
      context: "./frontend"
      args:
        - VITE_API_URL=http://localhost:8080/api
    ports:
      - "80:80"
    depends_on:
      - backend
